# Generated by Django 5.0.1 on 2024-01-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
