# Generated by Django 5.0.1 on 2024-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0002_myuser_otp_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='otp_secret_key',
        ),
    ]
