# Generated by Django 5.0.1 on 2024-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0003_remove_myuser_otp_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
