# Generated by Django 5.0.1 on 2024-01-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0004_myuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='otp',
        ),
    ]
