# Generated by Django 5.0.1 on 2024-01-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0005_remove_myuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='uploads/products/'),
        ),
    ]
