# Generated by Django 5.0.1 on 2024-01-31 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0006_products_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='accessories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='wired_or_TWS',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
