# Generated by Django 5.0.1 on 2024-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphonesapp', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
